"""Añadido campo horaSalida modelo salon

Revision ID: 77e0268d49c6
Revises: 65ee5edbdabc
Create Date: 2022-11-16 16:42:36.029239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e0268d49c6'
down_revision = '65ee5edbdabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horaSalida', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salon', schema=None) as batch_op:
        batch_op.drop_column('horaSalida')

    # ### end Alembic commands ###
