"""empty message

Revision ID: f5402c87bba2
Revises: 77e0268d49c6
Create Date: 2022-11-16 16:43:39.534147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5402c87bba2'
down_revision = '77e0268d49c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horaSalida', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salon', schema=None) as batch_op:
        batch_op.drop_column('horaSalida')

    # ### end Alembic commands ###
